### ISSUE TITLE
Не нужно подключать зависимости, которые вы не используете

### ISSUE THREAD

**Issue by coursar** [dilyarakhabibullina/taxiservice#3]
https://github.com/dilyarakhabibullina/taxiservice/blob/951ace92e8d8116b4e7d786e61bb6dbee1b90548/pom.xml#L17-L117

**Comment by dilyarakhabibullina** [comment]
удалила ненужные зависимости

**Comment by coursar** [comment]
Закрывать нужно сообщениями коммитов, а не руками
